### ISSUE TITLE
TOTP generation does not specify algorithm in generated URI

### ISSUE THREAD

**Issue by rf152** [privacyidea/privacyidea#384]
The URI is not including the algorithm

To reproduce:

Enrol Token
Select TOTP
Select SHA256 as algorithm
Enter other details
Generate Token

The URI contains no algorithm specification.

**Comment by cornelinux** [comment]
Am I recalling this right?
Last time I checked the Google Authenticator only supported SHA1?

Is there an App supporting SHA256?
(Nevertheless you a right, when choosing sha256 and trying to scan/import it, it should create an error).

**Comment by cornelinux** [comment]
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

**Comment by rf152** [comment]
Google Authenticator does indeed only work with SHA1, but FreeOTP (which is a FOSS from Red Hat) does work, and uses the same format to import OTPs.

FreeOTP: https://fedorahosted.org/freeotp/

**Comment by cornelinux** [comment]
oups. fixed in 9b275d1827720a87dd588928eb97c07106340898

**Comment by rf152** [comment]
This still does not work. I have implemented the changes in 9b275d1, and it still does not specify the hashlib

When changing components/config/views/config.token.totp.html (same, changing totp.hashlib to form.haslib) it starts to work from the admin interface, but still does not work from a limited user interface.

**Comment by cornelinux** [comment]
You should not change components/config/views/config.token.totp.html since this writes the token config. And the token config in fact uses totp.hashlib.

I rather assume, that your browser still has cached the old token.enroll.totp.html file.

**Comment by rf152** [comment]
I have tried clearing the cache, and it is still not changing the page.

As an additional issue, when there is a policy that specifies totp_hashlib, when a user is enrolling, it does not select the hashlib you have defined in the policy, and only selects sha1 as the haslib.

**Comment by cornelinux** [comment]
Unfortunately you are not very specific what does not work. (Well maybe I am good at guessing)

I can not reproduce your original statement:

 *   Enrol Token
 *   Select TOTP
 *   **Select SHA256 as algorithm**
 *   E nter other details
 *   Generate Token

**Comment by rf152** [comment]
You're right, I'm not specific. The admin configuration is now working - I was forgetting to change from sha1 to sha256. My apologies!

WRT the other issue that I described, here are the reproduction steps:

- Create policy (as defined below)
- Log in as an end user (to whom the policy is applied - mine are being pulled from AD)
- Enrol Token
- The only option is TOTP, the only additional options that you have are a PIN
- Enrol the token
- The QR code & URL do not specify the algorithm. Further investigation seems to imply that the algorithm is coming through as sha1, even though the policy should set it to 256.

```json
{ "otp_pin_contents": "nnnn", "setpin": true, "totp_hashlib": "sha256", "totp_otplen": "8", "totp_force_server_generate": true, "otp_pin_maxlength": "4", "resync": true, "totp_timestep": "30", "enrollTOTP": true, "auditlog": true, "otp_pin_minlength": "4" }
```

**Comment by cornelinux** [comment]
Thanks for being precise. Now I see: The hash algorithm is set in the policy, but the policy setting is not applied. (It works however, if the user sets the hash algorithm manually).

Looking at the code it seems that such settings are not at all applied. It also is true for hotp tokens. Hm, I think we have to choose a more generic approach to fix this.

I will open a new issue for this.
Thanks a lot for pointing this out!
